name: LocalBytes LocalDeck 24
service: esphome
event_type: esphome.localdeck_button
identifier_key: device_id
buttons:
  - x: 50
    y: 305
    width: 70
    height: 70
    conditions:
      - key: button
        value: 1
    actions:
      - title: press
        conditions:
          - key: type
            value: single
      - title: press 2x
        conditions:
          - key: type
            value: double
